(function() {
  module("R.sortBy");

  var sortBy = require('eigensheep/sort_by')['default'];

  test("sorts an array by a key generated by a given function", function() {
    var age = function(person) { return person.age };
    var family = [
      { name: "Julie", age: 27 },
      { name: "Mark", age: 29 },
      { name: "Belldandy", age: 7 }
    ];

    deepEqual(
      sortBy(age, family),
      [family[2], family[0], family[1]]
    );
  });
})();
